#!/bin/sh

if [ -f config.status ]; then
	make maintainer-clean
fi

./bootstrap && \
    ./configure CFLAGS='-DRPI2_BOARD' --enable-maintainer-mode \
		--enable-debug \
		--prefix=/usr \
		--sysconfdir=/etc $*
